### ISSUE TITLE
Upstream appears dead

### ISSUE THREAD

**Issue by Nemo157** [imp/cargo-multi#8]
https://gitlab.com/imp/cargo-multi gives me a 404, that's also the only place linked to from https://crates.io/crates/cargo-multi so if it's gone for good it would be nice to update the links there.

**Comment by imp** [comment]
Thanks for bringing this to my attention - it was a project misconfiguration after migrating to gitlab.
Please check now

**Comment by Nemo157** [comment]
It's working now 👍
