### ISSUE TITLE
Clap now swallows bare `--`

### ISSUE THREAD

**Issue by BenjaminGill-Metaswitch** [imp/cargo-multi#9]
This was fine when using clap 2.20.5. However, since updating to [2.21](https://github.com/kbknapp/clap-rs/blob/master/CHANGELOG.md#v2210-2017-03-09) (or above), I've started getting the following:

```
$ cargo multi fmt -- --write-mode=diff
-------------------------------------
Executing cargo fmt --write-mode=diff
-------------------------------------

crate1:
Unrecognized option: 'write-mode'.
usage: cargo fmt [options]

Options:
    -h, --help          show this message
    -q, --quiet         no output printed to stdout
    -v, --verbose       use verbose output
    -p, --package <package>
                        specify package to format (only usable in workspaces)
        --all           format all packages (only usable in workspaces)

This utility formats all bin and lib files of the current crate using rustfmt. Arguments after `--` are passed to rustfmt.

crate2:
Unrecognized option: 'write-mode'.
usage: cargo fmt [options]
...
```

Something has changed with the way clap handles arguments: it seems to silently swallow any number of bare `--`s. I'm not sure why this is, though.

Alternatively, pinning to a known-good version would suffice (`"~2.20.0").

**Comment by imp** [comment]
@BenjaminGill-Metaswitch I cannot reproduce this with the current clap (2.24.0). Can you please recheck ? If it is fixed I'd rather not lock the dependency on older release.

**Comment by imp** [comment]
@BenjaminGill-Metaswitch ping

**Comment by BenjaminGill-Metaswitch** [comment]
OK - thanks. This seems to have been fixed by the latest clap.
